/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.components;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JFrame;

/**
 *
 * @author gauravpunjabi
 */
public class SubjectComponent extends javax.swing.JPanel {

    /**
     * Creates new form SubjectComponent
     */
    public SubjectComponent(String subjectName,
                            String staffName,
                            boolean isLecture,
                            int roomNo) {
        initComponents();
        customInit(subjectName,staffName,isLecture,roomNo);
    }
    private void customInit(String subjectName,
                            String staffName,
                            boolean isLecutre,
                            int roomNo) {
        //Setting all the given values.
        this.jlSubject.setText(subjectName);
        this.jlStaff.setText(staffName);
        if(!isLecture) {
            this.jlType.setText("LEC");
            this.jlBatch.setVisible(false);
        }
        else {
            this.jlType.setText("LAB");
            this.jlBatch.setVisible(true);
        }
        this.jlRoom.setText("ROOM NO : " + roomNo);
        //Setting the default Foreground for the informative labels
        this.jlType.setForeground(Color.white);
        this.jlBatch.setForeground(Color.white);
        this.jlRoom.setForeground(Color.white);
        this.setSize(377,120);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlSubject = new javax.swing.JLabel();
        jlStaff = new javax.swing.JLabel();
        jlBatch = new javax.swing.JLabel(){
            @Override
            protected void paintComponent(Graphics g) {
                g.setColor(this.getBackground());
                g.fillRoundRect(0, 0, this.getWidth(), this.getHeight(), 10, 10);
                super.paintComponent(g);
            }
        };
        jlType = new javax.swing.JLabel(){
            @Override
            protected void paintComponent(Graphics g) {
                g.setColor(this.getBackground());
                g.fillRoundRect(0, 0, this.getWidth(), this.getHeight(), 10, 10);
                super.paintComponent(g);
            }
        };
        jlRoom = new javax.swing.JLabel(){
            @Override
            protected void paintComponent(Graphics g) {
                g.setColor(this.getBackground());
                g.fillRoundRect(0, 0, this.getWidth(), this.getHeight(), 10, 10);
                //        g.drawString("LAB", 5, 2);
                super.paintComponent(g);
            }
        };

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jlSubject.setFont(new java.awt.Font("Fira Sans", 0, 22)); // NOI18N
        jlSubject.setForeground(new java.awt.Color(89, 173, 249));
        jlSubject.setText("MANAGEMENT");
        jlSubject.setToolTipText("Subject name");
        add(jlSubject);
        jlSubject.setBounds(10, 10, 365, 38);

        jlStaff.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        jlStaff.setForeground(new java.awt.Color(203, 207, 215));
        jlStaff.setText("Nilima Mam");
        jlStaff.setToolTipText("Staff's Name");
        add(jlStaff);
        jlStaff.setBounds(10, 45, 350, 25);

        jlBatch.setBackground(new java.awt.Color(152, 94, 225));
        jlBatch.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N
        jlBatch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlBatch.setText("NO OF BATCHES : 3");
        jlBatch.setToolTipText("No of Batches.");
        add(jlBatch);
        jlBatch.setBounds(190, 90, 150, 20);

        jlType.setBackground(new java.awt.Color(236, 83, 93));
        jlType.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N
        jlType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlType.setText("LAB");
        jlType.setToolTipText("Lecture Type");
        add(jlType);
        jlType.setBounds(12, 90, 40, 20);

        jlRoom.setBackground(new java.awt.Color(246, 187, 95));
        jlRoom.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N
        jlRoom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlRoom.setText("ROOM NO: 103");
        jlRoom.setToolTipText("Room no");
        add(jlRoom);
        jlRoom.setBounds(60, 90, 120, 20);
    }// </editor-fold>//GEN-END:initComponents
    @Override
    protected void paintComponent(Graphics g) {
        g.setColor(Color.white);
        g.fillRoundRect(0,0,this.getWidth(),this.getHeight(),20,20);
    }
    public static void main(String[] args) {
        JFrame jf = new JFrame();
        jf.setLocationRelativeTo(null);
        jf.setUndecorated(true);
        jf.setShape(new RoundRectangle2D.Double(0,0,377,120,20,20));
        SubjectComponent component;
        component = new SubjectComponent("Advance Java","MRS.PRATIBHA PEDNEKAR",true,413);
        jf.setSize(377,120);
        jf.add(component);
        jf.getContentPane().setBackground(Color.LIGHT_GRAY);
        component.setVisible(true);
        component.setBounds(0,0,377,120);
        jf.setLayout(null);
        jf.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlBatch;
    private javax.swing.JLabel jlRoom;
    private javax.swing.JLabel jlStaff;
    private javax.swing.JLabel jlSubject;
    private javax.swing.JLabel jlType;
    // End of variables declaration//GEN-END:variables
    private String subjectName,staffName;
    private int roomNo;
    private boolean isLecture;
}
